Repository theforeman/foreman_remote_execution, pull requests merged in 2018-05, with the labels that each got.

#338 Fixes #22934 - work directories are being cleaned up now
  app/models/remote_execution_provider.rb
  app/models/setting/remote_execution.rb
  app/models/ssh_execution_provider.rb
  lib/foreman_remote_execution_core.rb
  lib/foreman_remote_execution_core/polling_script_runner.rb
  lib/foreman_remote_execution_core/script_runner.rb
  test/unit/remote_execution_provider_test.rb
Labels: Needs testing

#351 Refs #21731 - revert using `loop` instead of `process`
  lib/foreman_remote_execution_core/script_runner.rb
Labels: Needs testing

#335 Fixes #23016 - Fix setting refresh flag when retrieving output via API
  app/controllers/api/v2/job_invocations_controller.rb
  test/functional/api/v2/job_invocations_controller_test.rb
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#349 Fixes #22483 - use host.host_param instead of host.params if possible
  app/models/concerns/foreman_remote_execution/host_extensions.rb
  app/models/remote_execution_provider.rb
  app/models/ssh_execution_provider.rb
  test/unit/concerns/host_extensions_test.rb
  test/unit/remote_execution_provider_test.rb
Labels: Needs testing

#345 Fixes #19130 - dzdo support
  app/models/remote_execution_provider.rb
  lib/foreman_remote_execution_core/script_runner.rb
  test/unit/remote_execution_provider_test.rb
Labels: Needs testing, Not yet reviewed

#350 Fixes #20778 - handle selection of all hosts on all pages.
  app/controllers/job_invocations_controller.rb
  app/models/job_invocation_composer.rb
Labels: Needs testing

#352 Set the license in the gemspec
  foreman_remote_execution.gemspec
  foreman_remote_execution_core.gemspec
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#353 Remove duplicate license tag in core gemspec
  foreman_remote_execution_core.gemspec
Labels: Needs testing, Waiting on contributor
