Repository theforeman/foreman_remote_execution, pull requests merged in 2018-06, with the labels that each got.

#355 Fixes #23163 - Fix breadcrumbs in template invocation details
  app/controllers/api/v2/template_invocations_controller.rb
  app/views/api/v2/template_invocations/base.json.rabl
  app/views/api/v2/template_invocations/template_invocations.json.rabl
  app/views/template_invocations/show.html.erb
  config/routes.rb
  lib/foreman_remote_execution/engine.rb
  test/functional/api/v2/template_invocations_controller_test.rb
Labels: Needs re-review, Needs testing

#356 Fixes #23858 - Add welcome page for job invocations
  app/views/job_invocations/welcome.html.erb
Labels: Needs testing, Not yet reviewed

#357 Fixes #23891 - share all templates to all taxonomies
  .rubocop.yml
  db/seeds.d/70-job_templates.rb
Labels: Needs testing

#360 Fixes #24085 - Include missing link in breadcrumbs
  app/views/template_invocations/show.html.erb
Labels: Needs testing, Not yet reviewed

#359 Fixes #24074 - Access execution status in a find-or-create fashion
  app/lib/actions/remote_execution/run_host_job.rb
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#293 Fixes #21668 - Resilience
  app/lib/actions/remote_execution/run_hosts_job.rb
Labels: Needs testing
