Repository theforeman/foreman_remote_execution, pull requests merged in 2018-02, with the labels that each got.

#298 Fixes #22099 - reuse core exporting
  app/models/concerns/foreman_remote_execution/exportable.rb
  app/models/foreign_input_set.rb
  app/models/job_template.rb
  app/models/template_input.rb
  test/unit/concerns/exportable_test.rb
Labels: Ready to merge

#316 Fixes #22605 - JobInvocation API accepts 'feature' param
  .hound.yml
  app/controllers/api/v2/job_invocations_controller.rb
  test/functional/api/v2/job_invocations_controller_test.rb
Labels: Needs testing

#318 Fixes #22609 - customizable notifications per feature
  .rubocop.yml
  app/models/job_invocation.rb
  app/models/job_invocation_composer.rb
  app/models/remote_execution_feature.rb
  app/models/setting/remote_execution.rb
  app/views/job_invocations/_form.html.erb
  db/migrate/20180202072115_add_notification_builder_to_remote_execution_feature.rb
  db/migrate/20180202123215_add_feature_id_to_job_invocation.rb
  test/unit/job_invocation_composer_test.rb
Labels: Needs testing

#321 Fixes #22670 - Allow search query on JobInvocation API
  app/controllers/api/v2/job_invocations_controller.rb
  app/models/job_invocation_composer.rb
  test/functional/api/v2/job_invocations_controller_test.rb
Labels: Needs re-review, Needs testing

#317 Fixes #22604 - Accept input values as GET params in UI
  app/controllers/job_invocations_controller.rb
  app/models/job_invocation_composer.rb
  test/functional/job_invocations_controller_test.rb
Labels: Ready to merge
