Repository theforeman/foreman_remote_execution, pull requests merged in 2018-04, with the labels that each got.

#340 Fixes #23089 - drop dynflow dependency
  foreman_remote_execution.gemspec
Labels: Needs re-review, Needs testing

#341 Refs #22849 - update .rubocop_todo.yml
  .rubocop.yml
  .rubocop_todo.yml
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#130 Fixes #13333 - Use Patternfly cards to redesign job invocations
  .babelrc
  .eslintignore
  .eslintrc
  .gitignore
  .hound.yml
  .travis.yml
  app/assets/javascripts/foreman_remote_execution/template_invocation.js
  app/assets/stylesheets/foreman_remote_execution/job_invocations.css.scss
  app/controllers/job_invocations_controller.rb
  app/helpers/job_invocations_chart_helper.rb
  app/helpers/job_invocations_helper.rb
  app/helpers/remote_execution_helper.rb
  app/models/job_invocation.rb
  app/views/job_invocations/_card_results.html.erb
  app/views/job_invocations/_card_schedule.html.erb
  app/views/job_invocations/_card_target_hosts.html.erb
  app/views/job_invocations/_card_user_input.html.erb
  app/views/job_invocations/_tab_hosts.html.erb
  app/views/job_invocations/_tab_overview.html.erb
  app/views/job_invocations/_tab_preview_templates.html.erb
  app/views/job_invocations/_user_input.html.erb
  app/views/job_invocations/show.html.erb
  app/views/job_invocations/show.js.erb
  config/routes.rb
  lib/foreman_remote_execution/engine.rb
  package.json
  scripts/travis_run_js_tests.sh
  test/unit/job_invocation_test.rb
  webpack/index.js
  webpack/react_app/components/jobInvocations/AggregateStatus/index.js
  webpack/react_app/components/jobInvocations/AggregateStatus/index.test.js
  webpack/react_app/components/jobInvocations/index.js
  webpack/react_app/redux/actions/jobInvocations/index.js
  webpack/react_app/redux/consts.js
  webpack/react_app/redux/reducers/index.js
  webpack/react_app/redux/reducers/jobInvocations/index.fixtures.js
  webpack/react_app/redux/reducers/jobInvocations/index.js
  webpack/react_app/redux/reducers/jobInvocations/index.test.js
  webpack/test_setup.js
Labels: Needs testing

#343 Refs #21457 - Provide the expected interface in the base model
  app/models/remote_execution_provider.rb
Labels: Needs testing

#346 Fixes #23297 - Webpack assets path changed
  app/views/job_invocations/show.html.erb
Labels: Needs testing, Not yet reviewed

#333 Fixes #22993 - refactor audits definitions
  app/models/job_invocation.rb
  app/models/job_template.rb
Labels: Needs testing

#330 Fixes #20661 - use separate queue for rex jobs
  app/lib/actions/remote_execution/run_host_job.rb
  app/lib/actions/remote_execution/run_hosts_job.rb
  app/models/setting/remote_execution.rb
  lib/foreman_remote_execution/engine.rb
Labels: Ready to merge

#348 Fixes #22955 - Update host status on finalize
  app/lib/actions/remote_execution/run_host_job.rb
  app/models/host_status/execution_status.rb
  lib/foreman_remote_execution_core/fake_script_runner.rb
  test/unit/actions/run_host_job_test.rb
Labels: Needs testing, Not yet reviewed

#347 Fixes #21810 - fix total hosts count on job invocations page.
  app/helpers/remote_execution_helper.rb
Labels: Ready to merge

#344 Fixes #23239 - Migrate two-pane to breadcrumb-bar
  app/views/job_invocations/show.html.erb
  app/views/job_templates/edit.html.erb
  app/views/job_templates/index.html.erb
Labels: Needs testing

#325 Fixes #22700 - Use TriggerRepeat hook
  app/lib/actions/remote_execution/run_hosts_job.rb
  foreman_remote_execution.gemspec
Labels: Needs testing

#331 Fixes #22375 - uses new way of importing templates
  app/models/job_template.rb
  app/models/job_template_importer.rb
  test/unit/job_template_importer_test.rb
Labels: Needs testing, Not yet reviewed
