Repository theforeman/foreman_remote_execution, pull requests merged in 2018-12, with the labels that each got.

#399 Fixes #25598 - enhance dealing with new lines in UI console
  app/helpers/remote_execution_helper.rb
  app/views/template_invocations/_output_line_set.html.erb
  app/views/template_invocations/show.html.erb
  test/helpers/remote_execution_helper_test.rb
Labels: Needs testing, Waiting on contributor

#395 Fixes #25499 - Adapt to breadcrumb changes in core
  app/views/job_invocations/show.html.erb
Labels: Needs testing, Not yet reviewed

#400 Fixes #25127 - fix template loading from task - rebased
  app/helpers/remote_execution_helper.rb
Labels: Needs testing, Not yet reviewed

#381 Fixes #24483 - Provide raw output API endpoint
  app/controllers/api/v2/job_invocations_controller.rb
  config/routes.rb
  lib/foreman_remote_execution/engine.rb
  test/functional/api/v2/job_invocations_controller_test.rb
Labels: 1.20 candidate, Needs testing
