Repository theforeman/foreman_remote_execution, pull requests merged in 2018-07, with the labels that each got.

#362 Fixes #24113 - fix fake executor
  app/lib/actions/remote_execution/run_host_job.rb
  lib/foreman_remote_execution_core/fake_script_runner.rb
Labels: Needs testing

#361 Fixes #23394 - Unable to set effective user for job templates
  app/controllers/api/v2/job_templates_controller.rb
  test/functional/api/v2/job_templates_controller_test.rb
Labels: Needs testing

#365 fixes #24240 - replace render text with plain
  app/controllers/job_templates_controller.rb
  test/factories/foreman_remote_execution_factories.rb
  test/functional/job_templates_controller_test.rb
Labels: Needs testing, Not yet reviewed

#368 Fixes #24368 - Provide output for hosts which are not planned yet
  app/controllers/api/v2/job_invocations_controller.rb
  test/functional/api/v2/job_invocations_controller_test.rb
Labels: Needs testing, Not yet reviewed

#366 Fixes #24266 - Add taxonomies to job template export
  app/models/job_template.rb
  test/functional/api/v2/job_templates_controller_test.rb
  test/unit/job_template_test.rb
Labels: Ready to merge

#363 fixes #24130 - use new rendering engine
  app/lib/foreman_remote_execution/renderer/scope/input.rb
  app/models/input_template_renderer.rb
  app/models/template_input.rb
  lib/foreman_remote_execution/engine.rb
Labels: Needs testing, Not yet reviewed
