Repository theforeman/foreman_remote_execution, pull requests merged in 2018-11, with the labels that each got.

#393 refs #25402 - Sync templates
  app/views/templates/ssh/module_action.erb
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#391 Rubocop
  .rubocop.yml
  db/migrate/20150612121541_add_job_template_to_template.rb
  db/migrate/20160203104056_add_concurrency_options_to_job_invocation.rb
  db/migrate/20171129103615_add_secrets_to_job_invocations.rb
  test/functional/api/v2/foreign_input_sets_controller_test.rb
  test/functional/api/v2/job_invocations_controller_test.rb
  test/functional/api/v2/job_templates_controller_test.rb
  test/functional/api/v2/remote_execution_features_controller_test.rb
  test/unit/actions/run_host_job_test.rb
  test/unit/actions/run_hosts_job_test.rb
  test/unit/input_template_renderer_test.rb
  test/unit/job_invocation_composer_test.rb
  test/unit/job_invocation_test.rb
  test/unit/job_template_effective_user_test.rb
  test/unit/job_template_test.rb
  test/unit/remote_execution_feature_test.rb
  test/unit/targeting_test.rb
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#394 Fixes #21595 - Show Static Query in Job invocations overview
  app/views/job_invocations/index.html.erb
Labels: Needs testing

#388 Fixes #23898 - Allow setting per_page of hosts table
  app/controllers/job_invocations_controller.rb
Labels: 1.20 candidate, Needs testing
