Repository theforeman/foreman_remote_execution, pull requests merged in 2018-09, with the labels that each got.

#372 Fixes #24698 - RemoteExecutionFeature.register Rails 5.2 fix
  app/models/remote_execution_feature.rb
Labels: Needs testing

#374 Fixes #24866 - introduce caching for macros
  app/lib/actions/remote_execution/run_hosts_job.rb
  app/lib/foreman_remote_execution/renderer/scope/input.rb
  app/models/job_invocation.rb
  test/unit/renderer_scope_input.rb
Labels: Needs re-review, Needs testing

#375 Fixes #24866 - Backport template renderer caching for 1.5-stable
  app/lib/actions/remote_execution/run_hosts_job.rb
  app/models/input_template_renderer.rb
  app/models/job_invocation.rb
  test/unit/input_template_renderer_test.rb
Labels: Needs testing, Not yet reviewed

#378 Fixes #24930 - Make output fail with 404 when job is missing
  app/controllers/api/v2/job_invocations_controller.rb
  test/functional/api/v2/job_invocations_controller_test.rb
Labels: Needs testing

#380 Fixes #22209 - Render empty lines properly in output
  app/assets/stylesheets/foreman_remote_execution/template_invocation.css.scss
  app/helpers/job_invocation_output_helper.rb
  app/views/template_invocations/_output_line_set.html.erb
Labels: Needs testing

#379 Fixes #22750 - Rerun failed should rerun also on cancelled hosts
  app/helpers/job_invocations_helper.rb
  app/helpers/remote_execution_helper.rb
  app/models/job_invocation.rb
  test/factories/foreman_remote_execution_factories.rb
  test/functional/api/v2/job_invocations_controller_test.rb
  test/unit/job_invocation_test.rb
Labels: Needs testing

#382 Fixes #24989 - Modularity Templates for REX
  app/views/templates/ssh/module_action.erb
Labels: Needs testing, Not yet reviewed
