Repository theforeman/foreman_remote_execution, pull requests merged in 2018-03, with the labels that each got.

#287 Fixes #20496 - Add API for canceling jobs
  app/controllers/api/v2/job_invocations_controller.rb
  app/controllers/job_invocations_controller.rb
  app/helpers/remote_execution_helper.rb
  app/models/job_invocation.rb
  app/views/template_invocations/show.html.erb
  config/routes.rb
  lib/foreman_remote_execution/engine.rb
  test/functional/api/v2/job_invocations_controller_test.rb
Labels: Needs re-review, Needs testing

#290 Fixes #16991 - Allow setting ssh log level
  lib/foreman_remote_execution_core.rb
  lib/foreman_remote_execution_core/log_filter.rb
  lib/foreman_remote_execution_core/script_runner.rb
Labels: Needs re-review, Needs testing

#288 Fixes #20692 - Add API for rerunning jobs
  app/controllers/api/v2/job_invocations_controller.rb
  app/models/job_invocation_composer.rb
  config/routes.rb
  lib/foreman_remote_execution/engine.rb
  test/factories/foreman_remote_execution_factories.rb
  test/functional/api/v2/job_invocations_controller_test.rb
Labels: Needs re-review, Needs testing

#326 Refs #22609 - rename the field
  app/views/job_invocations/_form.html.erb
Labels: Needs testing

#324 Fixes #22697 - improve the invocation form
  app/views/job_invocations/_form.html.erb
  app/views/template_inputs/_invocation_form.html.erb
Labels: Needs testing

#322 Refs #22605 - fix params documentation
  app/controllers/api/v2/job_invocations_controller.rb
Labels: Needs testing

#327 Fixes #22773 - audit REX features user changes
  app/models/remote_execution_feature.rb
Labels: Needs testing, Not yet reviewed

#328 Fixes #22807 - Do not join on columns of possibly different types
  db/migrate/20160113162007_expand_all_template_invocations.rb
Labels: Needs testing, Not yet reviewed

#329 Fixes #22865 - Pull in the latest strings
  locale/action_names.rb
  locale/foreman_remote_execution.pot
Labels: Needs testing, Not yet reviewed

#334 Fixes #22740 - Fix unpermitted params error in API
  app/controllers/api/v2/job_invocations_controller.rb
Labels: Needs testing

#336 added asserts to template details test
  test/functional/api/v2/job_templates_controller_test.rb
Labels: Needs testing

#339 Fixes #22974 - store feature coming via form
  app/models/job_invocation_composer.rb
Labels: Needs testing, Not yet reviewed
