Repository theforeman/foreman_remote_execution, pull requests merged in 2019-11, with the labels that each got.

#442 Fixes #13139 - Provide autocompletion for search query
  app/views/job_invocations/_form.html.erb
Labels: Needs testing

#443 Fixes #25016 - Choose default job template in form
  app/models/job_invocation_composer.rb
  app/models/setting/remote_execution.rb
  app/views/job_invocations/_form.html.erb
  test/unit/job_invocation_composer_test.rb
Labels: Needs testing

#444 Fixes #28242 - Honor randomized ordering when rerunning failed job
  app/models/job_invocation_composer.rb
  test/unit/job_invocation_composer_test.rb
Labels: Needs testing, Not yet reviewed

#448 Fixes #28305 - cleanup assets
  app/assets/stylesheets/foreman_remote_execution/foreman_remote_execution.css
  app/assets/stylesheets/foreman_remote_execution/job_invocations.scss
  app/assets/stylesheets/foreman_remote_execution/modal_window.scss
  app/assets/stylesheets/foreman_remote_execution/template_invocation.scss
  app/views/job_invocations/_preview_hosts_modal.html.erb
  app/views/job_invocations/new.html.erb
  app/views/job_invocations/show.html.erb
  app/views/job_templates/_import_job_template_modal.html.erb
  app/views/template_invocations/show.html.erb
  lib/foreman_remote_execution/engine.rb
Labels: Ready to merge

#445 Fixes #28247 - Show chart overall result
  webpack/react_app/components/jobInvocations/index.js
Labels: Needs testing, Not yet reviewed

#450 Fixes #28333 - don't expose audit_comment in template view
  app/views/api/v2/job_templates/main.json.rabl
Labels: Needs testing

#452 Fixes #28348 - Register assets for precompilation
  lib/foreman_remote_execution/engine.rb
Labels: Needs testing
