Repository theforeman/foreman_remote_execution, pull requests merged in 2019-10, with the labels that each got.

#425 Fixes #27481 - Lay groundwork for provider secrets
  app/lib/actions/remote_execution/run_host_job.rb
  app/models/remote_execution_provider.rb
  app/models/ssh_execution_provider.rb
  test/unit/actions/run_host_job_test.rb
  test/unit/remote_execution_provider_test.rb
Labels: Needs testing

#437 Bump required foreman version to 1.24
  lib/foreman_remote_execution/engine.rb
Labels: Needs testing, Not yet reviewed

#438 Extract strings for translation
  locale/action_names.rb
  locale/foreman_remote_execution.pot
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#439 Fixes #28072 - Expand the systemd unit
  extra/cockpit/foreman-cockpit.service
Labels: Needs testing

#422 Pull in templates from community-templates
  app/views/templates/ssh/check_update.erb
  app/views/templates/ssh/package_action.erb
Labels: Needs testing, Waiting on contributor

#440 Refs #28072 - expand env and add SELinux wrapper
  extra/cockpit/foreman-cockpit
  extra/cockpit/foreman-cockpit.service
Labels: Needs testing

#441 Refs #28072 - remove SELinux wrapper
  extra/cockpit/foreman-cockpit
  extra/cockpit/foreman-cockpit.service
Labels: Needs testing
