Repository theforeman/foreman_remote_execution, pull requests merged in 2019-12, with the labels that each got.

#447 Fixes #28297 - rubocop updated to 0.75
  .rubocop.yml
  README.md
  extra/cockpit/foreman-cockpit-session
  foreman_remote_execution_core.gemspec
  lib/foreman_remote_execution/engine.rb
  locale/action_names.rb
Labels: Needs testing

#454 Fixes #28372 - Fix targeting autocompletion
  app/views/job_invocations/_form.html.erb
Labels: Needs testing

#449 Fixes #28314 - fixes autocomplete_search
  app/views/job_invocations/_tab_hosts.html.erb
Labels: Needs testing

#455 Fixes #28483 - Do not override remote_execution_ssh_keys parameter
  app/models/concerns/foreman_remote_execution/host_extensions.rb
  test/unit/concerns/host_extensions_test.rb
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#456 Fixes #28526 - Add ID to web console button
  app/helpers/concerns/foreman_remote_execution/hosts_helper_extensions.rb
Labels: Needs testing, Not yet reviewed

#446 Fixes #28255 - upgrade vendor to v3
  .babelrc
  .babelrc.js
  .gitignore
  package.json
  webpack/test_setup.js
Labels: Needs testing
