Repository theforeman/foreman_remote_execution, pull requests merged in 2019-07, with the labels that each got.

#417 Disable new Rubocop rules
  .rubocop.yml
Labels: Needs testing, Waiting on contributor

#418 Fixes #27325 - Enable autocomplete for job description
  app/models/job_invocation.rb
  test/unit/job_invocation_test.rb
Labels: Ready to merge

#420 Fixes #25991 - provide puppet run feature
  db/seeds.d/100-assign_features_with_templates.rb
  lib/foreman_remote_execution/engine.rb
Labels: Needs testing, Not yet reviewed

#419 Fixes #27302 - Make query type option more visible
  app/views/job_invocations/_form.html.erb
Labels: Needs testing
