Repository theforeman/foreman_remote_execution, pull requests merged in 2020-03, with the labels that each got.

#474 Fixes #29294 - Update Rubocop to 0.80
  .hound.yml
  .rubocop.yml
  .rubocop_todo.yml
  app/controllers/api/v2/job_invocations_controller.rb
  app/helpers/remote_execution_helper.rb
  app/lib/actions/remote_execution/run_host_job.rb
  app/models/concerns/foreman_remote_execution/errors_flattener.rb
  app/models/concerns/foreman_remote_execution/host_extensions.rb
  app/models/job_invocation_composer.rb
  app/models/remote_execution_feature.rb
  app/models/setting/remote_execution.rb
  lib/foreman_remote_execution_core/script_runner.rb
Labels: Needs testing

#470 Fixes #28997 - remove %{puppet_options} from the format_description
  app/models/job_invocation.rb
  test/unit/job_invocation_test.rb
Labels: Needs testing, Waiting on contributor

#473 Fixes #25149 - Warning for Job taxonomies in re-rerun
  app/controllers/job_invocations_controller.rb
  app/views/job_invocations/_form.html.erb
  app/views/job_invocations/_rerun_taxonomies.html.erb
Labels: Needs testing

#458 Fixes #28616 - Pass needed option to fix concurrency control
  app/lib/actions/remote_execution/run_host_job.rb
  app/lib/actions/remote_execution/run_hosts_job.rb
  app/views/job_invocations/_form.html.erb
Labels: Needs testing

#478 Fixes #29361 Add pagelet to Job invocation detail
  app/views/job_invocations/show.html.erb
Labels: Needs testing

#481 Fixes #29400 - add rubocop-minitest
  .rubocop.yml
  Gemfile
  test/functional/api/v2/job_invocations_controller_test.rb
  test/functional/api/v2/job_templates_controller_test.rb
  test/functional/api/v2/template_invocations_controller_test.rb
  test/unit/actions/run_hosts_job_test.rb
  test/unit/concerns/foreman_tasks_cleaner_extensions_test.rb
  test/unit/concerns/host_extensions_test.rb
  test/unit/concerns/nic_extensions_test.rb
  test/unit/execution_task_status_mapper_test.rb
  test/unit/input_template_renderer_test.rb
  test/unit/job_invocation_composer_test.rb
  test/unit/job_invocation_test.rb
  test/unit/job_template_effective_user_test.rb
  test/unit/job_template_test.rb
  test/unit/remote_execution_feature_test.rb
  test/unit/remote_execution_provider_test.rb
  test/unit/renderer_scope_input.rb
  test/unit/targeting_test.rb
Labels: Needs testing

#480 Fixes #29399 - Make schedule_job_multi_button method extendable
  app/helpers/concerns/foreman_remote_execution/hosts_helper_extensions.rb
Labels: Needs testing

#484 Fixes #29422 - web console should open in a new tab or window
  app/helpers/concerns/foreman_remote_execution/hosts_helper_extensions.rb
Labels: Needs re-review, Needs testing
