Repository theforeman/foreman_remote_execution, pull requests merged in 2020-07, with the labels that each got.

#513 Fixes #30237 - Allow regex meta-character in ssh password
  lib/foreman_remote_execution_core/script_runner.rb
Labels: Needs testing, Not yet reviewed

#511 Fixes #30213 - long host list breaks page
  app/assets/stylesheets/foreman_remote_execution/job_invocations.scss
  app/views/job_invocations/_card_target_hosts.html.erb
Labels: Needs testing

#516 Sync templates
  app/views/templates/ssh/package_action.erb
  app/views/templates/ssh/puppet_agent_disable.erb
  app/views/templates/ssh/puppet_agent_enable.erb
  app/views/templates/ssh/puppet_install_modules_from_forge.erb
  app/views/templates/ssh/puppet_run_once.erb
Labels: Needs testing, Waiting on contributor

#515 Fixes #30330 - Added word-wrap for description field
  app/assets/stylesheets/foreman_remote_execution/job_invocations.scss
  app/views/job_invocations/index.html.erb
Labels: Needs testing

#514 Fixes #30225 - Make ssh debug logging show useful data
  lib/foreman_remote_execution_core.rb
  lib/foreman_remote_execution_core/log_filter.rb
Labels: Needs testing

#519 Fixes #30406: default_capsule method exists on SmartProxy object
  app/services/default_proxy_proxy_selector.rb
Labels: Needs testing

#518 Fixes #30403 - Add DSL docs for REX plugin
  app/lib/foreman_remote_execution/renderer/scope/input.rb
  lib/foreman_remote_execution/engine.rb
Labels: Needs testing

#520 Fixes #27988 - Filter search "user = current_user" for Job Invocations
  app/models/job_invocation.rb
  db/seeds.d/20-permissions.rb
  test/functional/api/v2/job_invocations_controller_test.rb
  test/functional/job_invocations_controller_test.rb
  test/support/remote_execution_helper.rb
Labels: Ready to merge, Waiting on contributor

#508 Fixes #30188 - Provide the ability to use su with password
  app/lib/actions/remote_execution/run_host_job.rb
  app/lib/actions/remote_execution/run_hosts_job.rb
  app/models/job_invocation.rb
  app/models/job_invocation_composer.rb
  app/models/remote_execution_provider.rb
  app/models/setting/remote_execution.rb
  app/models/ssh_execution_provider.rb
  app/views/job_invocations/_form.html.erb
  db/migrate/20200623073022_rename_sudo_password_to_effective_user_password.rb
  lib/foreman_remote_execution_core/script_runner.rb
  test/unit/actions/run_host_job_test.rb
  test/unit/actions/run_hosts_job_test.rb
  test/unit/job_invocation_composer_test.rb
  test/unit/remote_execution_provider_test.rb
Labels: Ready to merge

#517 Fixes #30399 - Fix error when deleting discovered hosts
  app/models/concerns/foreman_remote_execution/orchestration/ssh.rb
Labels: Needs testing

#521 Fixes #30513 - Return resolved hosts after creating a job using API
  app/controllers/api/v2/job_invocations_controller.rb
Labels: Needs testing, Waiting on contributor
