Repository theforeman/foreman_remote_execution, pull requests merged in 2020-10, with the labels that each got.

#540 Fixes #30947 - replace the notice flash type
  app/controllers/job_templates_controller.rb
Labels: Needs testing

#537 Fixes #30902 - Allow searching job invocations by id
  app/models/job_invocation.rb
Labels: Needs testing

#542 Resolve issue when viewing successful job invocation
  app/views/template_invocations/_output_line_set.html.erb
Labels: Needs testing, Waiting on contributor

#535 Fixes #30859 - Prevent job from getting stuck after first batch
  app/lib/actions/remote_execution/run_hosts_job.rb
  test/unit/actions/run_hosts_job_test.rb
Labels: Needs testing, Not yet reviewed

#544 Fixes #31046 - update js vendor to 4.14.0
  package.json
Labels: Needs testing

#543 Fixes #31012 - API for retrieving outputs for multiple hosts
  app/controllers/api/v2/job_invocations_controller.rb
  config/routes.rb
  lib/foreman_remote_execution/engine.rb
  test/functional/api/v2/job_invocations_controller_test.rb
Labels: Needs testing

#545 Fixes #31109 - use non-interactive mode
  app/views/templates/ssh/package_action.erb
Labels: Needs testing

#538 Refs #30816 - Show host id for template input
  app/views/api/v2/job_invocations/main.json.rabl
Labels: Needs testing
