Repository theforeman/foreman_remote_execution, pull requests merged in 2020-02, with the labels that each got.

#467 Fixes #27324 - Add Jobs button to host detail page
  app/helpers/concerns/foreman_remote_execution/hosts_helper_extensions.rb
  lib/foreman_remote_execution/engine.rb
Labels: Needs testing

#468 Fixes #25144 - Include taxonomies in Job invocation targeting
  app/controllers/concerns/foreman/controller/parameters/targeting.rb
  app/helpers/job_invocations_helper.rb
  app/models/job_invocation_composer.rb
  app/models/targeting.rb
  app/views/api/v2/job_invocations/main.json.rabl
  app/views/job_invocations/_card_target_hosts.html.erb
  app/views/job_invocations/_form.html.erb
  db/migrate/20200204123702_targeting_add_taxonomies.rb
Labels: Needs testing

#472 Fixes #25144 - Display taxonomies on Job invocation pages
  app/controllers/job_invocations_controller.rb
  app/helpers/job_invocations_helper.rb
  app/views/job_invocations/_card_target_hosts.html.erb
Labels: Needs testing, Not yet reviewed

#465 Fixes #28826 - Describe connect_by_ip only applies to IPv4
  app/models/setting/remote_execution.rb
Labels: Needs testing

#471 Fixes #29048 - cant create job with end time
  app/models/job_invocation_composer.rb
  test/unit/job_invocation_composer_test.rb
Labels: Needs testing

#469 Fixes #28975 - Add description to plugin roles
  lib/foreman_remote_execution/engine.rb
Labels: Ready to merge
