Repository theforeman/foreman_remote_execution, pull requests merged in 2020-06, with the labels that each got.

#490 Fixes #29783 - Allow overriding proxy selector in jobs
  app/lib/actions/remote_execution/run_host_job.rb
  app/models/remote_execution_provider.rb
  app/services/default_proxy_proxy_selector.rb
Labels: Needs testing

#498 Use GitHub actions as CI
  .github/workflows/ci.yml
  .rubocop_todo.yml
  foreman_remote_execution.gemspec
  locale/action_names.rb
Labels: Needs testing, Waiting on contributor

#504 Fixes #30015 - remove rubocop from .hound.yml
  .hound.yml
Labels: Needs testing

#505 Disable TravisCI in favor of GH actions
  .travis.yml
  scripts/travis_run_js_tests.sh
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#501 Fixes #29962 - Make known hosts key removal less error prone
  app/models/concerns/foreman_remote_execution/orchestration/ssh.rb
  test/models/orchestration/ssh_test.rb
Labels: Needs testing

#506 Fixes #30051 - Set rubocop version to same as for Foreman
  Gemfile
  foreman_remote_execution.gemspec
Labels: Needs testing

#493 Fixes #28723 - Job Invocations page slow loading for non-admin users
  app/helpers/remote_execution_helper.rb
  app/views/job_invocations/_host_actions_td.html.erb
  app/views/job_invocations/_host_name_td.html.erb
  app/views/job_invocations/_host_status_td.html.erb
  app/views/job_invocations/_tab_hosts.html.erb
  app/views/job_invocations/show.html.erb
  app/views/job_invocations/show.js.erb
  app/views/job_invocations/show.json.erb
  webpack/__mocks__/foremanReact/common/I18n.js
  webpack/__mocks__/foremanReact/components/common/ActionButtons/ActionButtons.js
  webpack/__mocks__/foremanReact/constants.js
  webpack/index.js
  webpack/react_app/components/TargetingHosts/TargetingHosts.js
  webpack/react_app/components/TargetingHosts/TargetingHostsActions.js
  webpack/react_app/components/TargetingHosts/TargetingHostsConsts.js
  webpack/react_app/components/TargetingHosts/TargetingHostsSelectors.js
  webpack/react_app/components/TargetingHosts/__tests__/HostItem.test.js
  webpack/react_app/components/TargetingHosts/__tests__/HostStatus.test.js
  webpack/react_app/components/TargetingHosts/__tests__/TargetingHosts.test.js
  webpack/react_app/components/TargetingHosts/__tests__/__snapshots__/HostItem.test.js.snap
  webpack/react_app/components/TargetingHosts/__tests__/__snapshots__/HostStatus.test.js.snap
  webpack/react_app/components/TargetingHosts/__tests__/__snapshots__/TargetingHosts.test.js.snap
  webpack/react_app/components/TargetingHosts/__tests__/fixtures.js
  webpack/react_app/components/TargetingHosts/components/HostItem.js
  webpack/react_app/components/TargetingHosts/components/HostStatus.js
  webpack/react_app/components/TargetingHosts/index.js
Labels: Needs testing, Waiting on contributor

#503 RM#29972 - API::JobInvocations - Host permissions
  app/controllers/api/v2/job_invocations_controller.rb
  app/controllers/api/v2/template_invocations_controller.rb
  app/helpers/job_invocations_helper.rb
  app/views/api/v2/job_invocations/main.json.rabl
  test/functional/api/v2/job_invocations_controller_test.rb
Labels: Needs testing, Waiting on contributor

#507 Fixes #30068 - Allow remote_execution_ssh_keys to be a string
  app/models/concerns/foreman_remote_execution/host_extensions.rb
  test/unit/concerns/host_extensions_test.rb
Labels: Needs testing, Waiting on contributor

#494 Fixes #29867 - API - Show job status for each host on JobInvocation detail
  app/controllers/api/v2/job_invocations_controller.rb
  app/views/api/v2/job_invocations/main.json.rabl
Labels: Needs testing, Waiting on contributor

#510 Fixes #30212 - API::JobInvocations#show - change host_status param to boolean
  app/controllers/api/v2/job_invocations_controller.rb
  app/views/api/v2/job_invocations/main.json.rabl
Labels: Needs testing, Waiting on contributor

#512 Update apt cache before installing packages in GH action
  .github/workflows/ci.yml
Labels: Needs testing, Not yet reviewed, Waiting on contributor
