Repository theforeman/foreman_remote_execution, pull requests merged in 2020-08, with the labels that each got.

#523 Fixes #30525 - Disable task buttons when job finishes
  app/controllers/job_invocations_controller.rb
  app/views/job_invocations/show.html.erb
  app/views/job_invocations/show.js.erb
Labels: Needs testing, Waiting on contributor

#522 Fixes #30503 - Catch 404 from known host removal properly
  app/models/concerns/foreman_remote_execution/orchestration/ssh.rb
  test/models/orchestration/ssh_test.rb
Labels: Needs testing, Not yet reviewed

#524 Fixes #30582 - host search filter does not work in job invocation page
  webpack/react_app/components/TargetingHosts/TargetingHosts.js
  webpack/react_app/components/TargetingHosts/__tests__/__snapshots__/TargetingHosts.test.js.snap
Labels: Needs testing, Waiting on contributor

#525 Fixes #30628 - show empty hosts in job invocation api
  app/views/api/v2/job_invocations/main.json.rabl
  test/functional/api/v2/job_invocations_controller_test.rb
Labels: Needs testing

#526 Fixes #30628 - show empty hosts in job invocation api cp 3.3
  app/views/api/v2/job_invocations/main.json.rabl
  test/functional/api/v2/job_invocations_controller_test.rb
Labels: Needs testing

#531 Fixes #30685 - Ensure run button appears in job templates page
  lib/foreman_remote_execution/engine.rb
Labels: Needs testing

#527 Fixes #30651 - Expose subnet-rex proxy associations in the API
  app/controllers/foreman_remote_execution/concerns/api/v2/subnets_controller_extensions.rb
  app/views/api/v2/subnets/remote_execution_proxies.json.rabl
  lib/foreman_remote_execution/engine.rb
Labels: Needs testing
