Repository theforeman/foreman_remote_execution, pull requests merged in 2021-05, with the labels that each got.

#569 Fixes #32081 - Add provider specific inputs
  app/controllers/api/v2/job_invocations_controller.rb
  app/lib/foreman_remote_execution/provider_input.rb
  app/models/invocation_provider_input_value.rb
  app/models/job_invocation_composer.rb
  app/models/remote_execution_provider.rb
  app/models/template_invocation.rb
  app/views/job_invocations/_form.html.erb
  db/migrate/20210312074713_add_provider_inputs.rb
  test/unit/job_invocation_composer_test.rb
Labels: Needs testing

#588 Fixes #27770 - Add support for ed25519 keys
  foreman_remote_execution_core.gemspec
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#589 Fixes #32571 - fix reducers and fills not loading
  lib/foreman_remote_execution/engine.rb
  webpack/fills_index.js
  webpack/global_index.js
  webpack/index.js
  webpack/react_app/extend/fillRecentJobsCard.js
  webpack/react_app/extend/fillregistrationAdvanced.js
  webpack/react_app/extend/reducers.js
Labels: Needs testing

#581 Fixes #32107 - job invocation create API should work with the feature param
  app/controllers/api/v2/job_invocations_controller.rb
  app/models/job_invocation_composer.rb
  test/functional/api/v2/job_invocations_controller_test.rb
  test/unit/job_invocation_composer_test.rb
Labels: Needs testing, Waiting on contributor

#585 Fixes #32439 - Add error state to job wizard
  webpack/JobWizard/JobWizardSelectors.js
  webpack/JobWizard/steps/CategoryAndTemplate/CategoryAndTemplate.js
  webpack/JobWizard/steps/CategoryAndTemplate/CategoryAndTemplate.test.js
  webpack/JobWizard/steps/CategoryAndTemplate/__snapshots__/CategoryAndTemplate.test.js.snap
  webpack/JobWizard/steps/CategoryAndTemplate/index.js
  webpack/JobWizard/steps/form/GroupedSelectField.js
  webpack/JobWizard/steps/form/SelectField.js
  webpack/__mocks__/foremanReact/redux/API/APISelectors.js
Labels: Needs testing

#594 Refs #31267 - import icons from the main module, not dist
  webpack/react_app/components/RecentJobsCard/RecentJobsCard.js
Labels: Needs testing

#592 Address rubocop failures
  app/controllers/api/v2/job_invocations_controller.rb
  app/controllers/job_templates_controller.rb
  app/helpers/job_invocations_helper.rb
  app/helpers/remote_execution_helper.rb
  app/lib/actions/remote_execution/run_host_job.rb
  app/models/concerns/foreman_remote_execution/host_extensions.rb
  app/models/job_invocation.rb
  app/models/job_invocation_composer.rb
  app/models/ssh_execution_provider.rb
  app/overrides/execution_interface.rb
  app/overrides/subnet_proxies.rb
  db/migrate/20180110104432_rename_template_invocation_permission.rb
  db/migrate/20190111153330_remove_remote_execution_without_proxy_setting.rb
  extra/cockpit/foreman-cockpit-session
Labels: Needs testing, Waiting on contributor

#584 Fixes #32357 - integrate rex features with webhooks
  app/lib/actions/remote_execution/run_host_job.rb
  lib/foreman_remote_execution/engine.rb
Labels: Needs testing

#593 Fixes #32628 - Add search definitions for jobs
  app/models/host_status/execution_status.rb
  app/models/job_invocation.rb
Labels: Needs testing

#553 Fixes #31441 - Add basic page for advanced in job wizard
  app/controllers/ui_job_wizard_controller.rb
  config/routes.rb
  lib/foreman_remote_execution/engine.rb
  package.json
  webpack/JobWizard/JobWizard.js
  webpack/JobWizard/JobWizard.scss
  webpack/JobWizard/JobWizardConstants.js
  webpack/JobWizard/JobWizardSelectors.js
  webpack/JobWizard/__tests__/JobWizard.test.js
  webpack/JobWizard/__tests__/__snapshots__/JobWizard.test.js.snap
  webpack/JobWizard/__tests__/__snapshots__/integration.test.js.snap
  webpack/JobWizard/__tests__/fixtures.js
  webpack/JobWizard/__tests__/integration.test.js
  webpack/JobWizard/steps/AdvancedFields/AdvancedFields.js
  webpack/JobWizard/steps/AdvancedFields/Fields.js
  webpack/JobWizard/steps/AdvancedFields/__tests__/AdvancedFields.test.js
  webpack/JobWizard/steps/AdvancedFields/__tests__/__snapshots__/AdvancedFields.test.js.snap
  webpack/JobWizard/steps/CategoryAndTemplate/CategoryAndTemplate.js
  webpack/JobWizard/steps/CategoryAndTemplate/__snapshots__/CategoryAndTemplate.test.js.snap
  webpack/JobWizard/steps/CategoryAndTemplate/index.js
  webpack/JobWizard/steps/form/FormHelpers.js
  webpack/JobWizard/steps/form/GroupedSelectField.js
  webpack/JobWizard/steps/form/SelectField.js
  webpack/JobWizard/steps/form/__tests__/__snapshots__/GroupedSelectField.test.js.snap
  webpack/JobWizard/steps/form/__tests__/__snapshots__/SelectField.test.js.snap
  webpack/__mocks__/foremanReact/redux/API/APISelectors.js
  webpack/react_app/components/TargetingHosts/__tests__/TargetingHostsSelectors.test.js
  webpack/react_app/components/TargetingHosts/__tests__/__snapshots__/TargetingHostsSelectors.test.js.snap
Labels: Needs testing
