Repository theforeman/foreman_remote_execution, pull requests merged in 2021-08, with the labels that each got.

#640 Fixes #32496 - Append usual paths to the end of PATH for power action
  app/views/templates/ssh/power_action.erb
Labels: Needs testing, Not yet reviewed

#639 Fixes #33163 - Fix ISE when viewing cancelled scheduled job
  app/lib/actions/remote_execution/run_hosts_job.rb
Labels: Needs testing, Not yet reviewed

#636 Refs #33024 - Do not crash during seeding if feature does not exist
  app/models/job_invocation_composer.rb
  app/models/remote_execution_feature.rb
Labels: Needs backporting, Needs testing, Not yet reviewed

#623 Fixes #32675 - Perform host cancel without following the link
  app/helpers/remote_execution_helper.rb
Labels: Needs backporting, Needs testing

#613 Completely drop foreman_remote_execution_core
  foreman_remote_execution.gemspec
  foreman_remote_execution_core.gemspec
  lib/foreman_remote_execution_core.rb
  lib/foreman_remote_execution_core/actions.rb
  lib/foreman_remote_execution_core/version.rb
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#617 Fixes #31705 - Handle timezones when scheduling jobs through API
  app/models/job_invocation_composer.rb
Labels: Needs testing

#635 Fixes #33143 - hide rex buttons for unpriviledged
  app/helpers/concerns/foreman_remote_execution/hosts_helper_extensions.rb
Labels: Needs testing

#614 Fixes #32606 - Reimplement known host key removal
  app/lib/actions/remote_execution/run_host_job.rb
  app/models/concerns/foreman_remote_execution/host_extensions.rb
  app/models/concerns/foreman_remote_execution/orchestration/ssh.rb
  app/models/concerns/foreman_remote_execution/smart_proxy_extensions.rb
  app/models/host_proxy_invocation.rb
  db/migrate/2021051713291621250977_add_host_proxy_invocations.rb
  lib/foreman_remote_execution/engine.rb
  test/models/orchestration/ssh_test.rb
Labels: Needs testing, Not yet reviewed

#608 Fixes #32951 - Add rerun button to template invocations
  app/views/template_invocations/show.html.erb
Labels: Needs testing, Needs re-review

#642 Fixes #33002 - Do not use deprecated net-ssh options
  foreman_remote_execution_core.gemspec
  lib/foreman_remote_execution_core/script_runner.rb
Labels: Needs testing, Not yet reviewed

#603 Fixes #32676 - Add status of REX jobs on dashboard
  app/models/job_invocation.rb
  app/views/dashboard/_latest-jobs.html.erb
  lib/foreman_remote_execution/engine.rb
Labels: Needs testing, Needs re-review

#577 Fixes #29384 - Connect by IP: Prefer IPv6 over IPv4
  app/models/remote_execution_provider.rb
  app/models/setting/remote_execution.rb
  test/unit/remote_execution_provider_test.rb
Labels: Needs testing, Not yet reviewed

#556 Fixes #31492 - Add basic hosts and inputs page
  webpack/JobWizard/JobWizard.js
  webpack/JobWizard/JobWizard.scss
  webpack/JobWizard/JobWizardConstants.js
  webpack/JobWizard/__tests__/fixtures.js
  webpack/JobWizard/__tests__/integration.test.js
  webpack/JobWizard/steps/AdvancedFields/AdvancedFields.js
  webpack/JobWizard/steps/AdvancedFields/__tests__/AdvancedFields.test.js
  webpack/JobWizard/steps/CategoryAndTemplate/CategoryAndTemplate.js
  webpack/JobWizard/steps/CategoryAndTemplate/CategoryAndTemplate.test.js
  webpack/JobWizard/steps/HostsAndInputs/SelectedChips.js
  webpack/JobWizard/steps/HostsAndInputs/TemplateInputs.js
  webpack/JobWizard/steps/HostsAndInputs/__tests__/SelectedChips.test.js
  webpack/JobWizard/steps/HostsAndInputs/__tests__/TemplateInputs.test.js
  webpack/JobWizard/steps/HostsAndInputs/index.js
  webpack/JobWizard/steps/Schedule/index.js
  webpack/JobWizard/steps/form/Formatter.js
  webpack/JobWizard/steps/form/WizardTitle.js
Labels: Needs testing
