Repository theforeman/foreman_remote_execution, pull requests merged in 2021-09, with the labels that each got.

#649 Fixes #33409 - Add facility for injecting alternative names
  app/lib/actions/remote_execution/run_host_job.rb
  app/models/remote_execution_provider.rb
Labels: Needs testing

#601 Fixes #32854 - allow proxy_batch_size to work properly
  app/lib/actions/remote_execution/run_hosts_job.rb
  test/unit/actions/run_hosts_job_test.rb
Labels: Needs testing, Needs re-review

#627 Fixes #33108 - Add start_at for job recurrence
  app/models/job_invocation_composer.rb
  test/functional/api/v2/job_invocations_controller_test.rb
Labels: Needs testing

#651 Fix tests broken by core changes
  test/unit/job_invocation_report_template_test.rb
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#638 Fixes #31564 - add email notification
  .rubocop_todo.yml
  app/lib/actions/remote_execution/run_hosts_job.rb
  app/mailers/rex_job_mailer.rb
  app/models/rex_mail_notification.rb
  app/services/ui_notifications/remote_execution_jobs/base_job_finish.rb
  app/views/rex_job_mailer/job_finished.html.erb
  app/views/rex_job_mailer/job_finished.text.erb
  db/seeds.d/50-notification_blueprints.rb
  db/seeds.d/95-mail_notifications.rb
  test/unit/actions/run_hosts_job_test.rb
Labels: Needs testing, Not yet reviewed, Demo worthy

#645 Refs #33311 - fix recent audit card alignment
  webpack/react_app/components/RecentJobsCard/RecentJobsCard.js
Labels: Needs testing, Waiting on contributor

#624 Fixes #33087 - Add password options to hammer REX job
  app/controllers/api/v2/job_invocations_controller.rb
  app/models/job_invocation_composer.rb
Labels: Needs testing, Needs re-review

#566 Fixes #32032 - proxy batch sizing per provider
  app/lib/actions/remote_execution/run_hosts_job.rb
  app/models/remote_execution_provider.rb
  test/unit/actions/run_hosts_job_test.rb
Labels: Needs testing, Not yet reviewed

#605 Fixes #32847 - job wizard description field with user data
  webpack/JobWizard/JobWizard.js
  webpack/JobWizard/__tests__/fixtures.js
  webpack/JobWizard/steps/AdvancedFields/AdvancedFields.js
  webpack/JobWizard/steps/AdvancedFields/DescriptionField.js
  webpack/JobWizard/steps/AdvancedFields/__tests__/AdvancedFields.test.js
  webpack/JobWizard/steps/AdvancedFields/__tests__/DescriptionField.test.js
Labels: Needs testing

#650 Fixes #32677 - Remove refresh tooltip after form refresh
  app/views/job_invocations/refresh.js.erb
Labels: Needs testing, Not yet reviewed, Needs backporting

#615 Fixes #33007 - Handle taxonomies gracefully on output endpoints
  app/controllers/api/v2/job_invocations_controller.rb
  test/functional/api/v2/job_invocations_controller_test.rb
Labels: Needs testing, Not yet reviewed
