Repository theforeman/foreman_remote_execution, pull requests merged in 2021-06, with the labels that each got.

#587 Fixes #32542 - Make REX core only a compatibility layer proxy plugin
  app/models/job_invocation_composer.rb
  app/models/remote_execution_provider.rb
  foreman_remote_execution.gemspec
  foreman_remote_execution_core.gemspec
  lib/foreman_remote_execution_core.rb
  lib/foreman_remote_execution_core/actions.rb
  lib/foreman_remote_execution_core/async_scripts/control.sh
  lib/foreman_remote_execution_core/async_scripts/retrieve.sh
  lib/foreman_remote_execution_core/dispatcher.rb
  lib/foreman_remote_execution_core/fake_script_runner.rb
  lib/foreman_remote_execution_core/log_filter.rb
  lib/foreman_remote_execution_core/polling_script_runner.rb
  lib/foreman_remote_execution_core/script_runner.rb
Labels: Needs testing, Waiting on contributor

#598 Fixes #32742 - Ensure job rerun through api works with invalid hosts
  app/models/job_invocation_composer.rb
  app/models/targeting.rb
  test/unit/job_invocation_composer_test.rb
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#599 Fixes #32797 - Fix issue that monitor > jobs page could not render
  app/models/job_invocation.rb
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#602 Fixes #32873 - Do not check bookmark permissions
  app/models/job_invocation_composer.rb
  test/unit/job_invocation_composer_test.rb
Labels: Needs testing, Not yet reviewed
