Repository theforeman/foreman_remote_execution, pull requests merged in 2021-03, with the labels that each got.

#571 Fixes #32114 - Host init config template in registration tests
  test/functional/api/v2/registration_controller_test.rb
Labels: Needs testing

#562 Fixes #31737 - Mark RunHostsJob as observable
  app/lib/actions/remote_execution/run_host_job.rb
  foreman_remote_execution.gemspec
  lib/foreman_remote_execution/engine.rb
Labels: Needs testing, Waiting on dependencies

#565 Fixes #31933 - Mark output as complete if task is missing
  app/controllers/api/v2/job_invocations_controller.rb
  app/models/job_invocation.rb
  test/functional/api/v2/job_invocations_controller_test.rb
Labels: Needs testing

#572 Refs #31737 - Show RunHostsJob jail doc in section "all"
  app/lib/actions/remote_execution/run_host_job.rb
Labels: Needs testing

#573 Fixes #32209 - Try to require task launcher registry in advance
  lib/foreman_remote_execution_core.rb
Labels: Needs testing, Waiting on contributor

#576 Fixes #32227 - Do not enhance Jenkins rake task
  lib/tasks/foreman_remote_execution_tasks.rake
Labels: Needs testing
