Repository theforeman/foreman_remote_execution, pull requests merged in 2021-04, with the labels that each got.

#575 Fixes #32219 - Check if SPDC settings are available
  lib/foreman_remote_execution_core.rb
Labels: Needs testing

#568 Fixes #32065 - Undeclared :error_message instance field
  app/lib/foreman_remote_execution/renderer/scope/input.rb
Labels: Needs testing

#551 Fixes #31342 - add Category and template step to job wizard
  package.json
  webpack/JobWizard/JobWizard.js
  webpack/JobWizard/JobWizard.scss
  webpack/JobWizard/JobWizardConstants.js
  webpack/JobWizard/JobWizardSelectors.js
  webpack/JobWizard/__tests__/JobWizard.test.js
  webpack/JobWizard/__tests__/__snapshots__/JobWizard.test.js.snap
  webpack/JobWizard/steps/CategoryAndTemplate/CategoryAndTemplate.js
  webpack/JobWizard/steps/CategoryAndTemplate/CategoryAndTemplate.test.js
  webpack/JobWizard/steps/CategoryAndTemplate/__snapshots__/CategoryAndTemplate.test.js.snap
  webpack/JobWizard/steps/CategoryAndTemplate/index.js
  webpack/JobWizard/steps/form/GroupedSelectField.js
  webpack/JobWizard/steps/form/SelectField.js
  webpack/JobWizard/steps/form/__tests__/GroupedSelectField.test.js
  webpack/JobWizard/steps/form/__tests__/SelectField.test.js
  webpack/JobWizard/steps/form/__tests__/__snapshots__/GroupedSelectField.test.js.snap
  webpack/JobWizard/steps/form/__tests__/__snapshots__/SelectField.test.js.snap
  webpack/__mocks__/foremanReact/common/helpers.js
  webpack/__mocks__/foremanReact/redux/API/index.js
  webpack/__mocks__/foremanReact/routes/common/PageLayout/PageLayout.js
Labels: Needs testing

#561 Fixes #31711 - Extend API params for generating registration command
  app/controllers/foreman_remote_execution/concerns/api/v2/registration_commands_controller_extensions.rb
  app/views/foreman/registration_commands/_form.html.erb
  lib/foreman_remote_execution/engine.rb
Labels: Ready to merge

#574 Fixes #32218 - Host Registration - New form
  app/views/foreman/registration_commands/_form.html.erb
  lib/foreman_remote_execution/engine.rb
  webpack/fills_index.js
  webpack/react_app/components/RegistrationExtension/RexInterface.js
  webpack/react_app/components/RegistrationExtension/__tests__/RexInterface.test.js
  webpack/react_app/components/RegistrationExtension/__tests__/__snapshots__/RexInterface.test.js.snap
Labels: Needs testing

#453 fixes #15265 - making reporting of tasks
  app/helpers/remote_execution_helper.rb
  app/models/job_invocation.rb
  app/models/setting/remote_execution.rb
  app/services/renderer_methods.rb
  foreman_remote_execution.gemspec
  lib/foreman_remote_execution/engine.rb
  test/helpers/remote_execution_helper_test.rb
  test/unit/job_invocation_report_template_test.rb
Labels: Needs testing

#580 Translations
  locale/action_names.rb
  locale/de/foreman_remote_execution.po
  locale/en/foreman_remote_execution.po
  locale/en_GB/foreman_remote_execution.po
  locale/es/foreman_remote_execution.po
  locale/foreman_remote_execution.pot
  locale/fr/foreman_remote_execution.po
  locale/ja/foreman_remote_execution.po
  locale/ko/foreman_remote_execution.po
  locale/pt_BR/foreman_remote_execution.po
  locale/ru/foreman_remote_execution.po
  locale/zh_CN/foreman_remote_execution.po
  locale/zh_TW/foreman_remote_execution.po
Labels: Needs testing, Waiting on contributor

#549 Fixes #31267 - Add recent jobs card to host details page
  lib/foreman_remote_execution/engine.rb
  package.json
  webpack/global_index.js
  webpack/index.js
  webpack/react_app/components/RecentJobsCard/RecentJobsCard.js
  webpack/react_app/components/RecentJobsCard/constants.js
  webpack/react_app/components/RecentJobsCard/index.js
  webpack/react_app/components/RecentJobsCard/styles.css
  webpack/react_app/extend/fills.js
  webpack/react_app/extend/reducers.js
Labels: Needs testing, Not yet reviewed
