Repository theforeman/foreman_remote_execution, pull requests merged in 2021-07, with the labels that each got.

#554 Fixes #31459 - Add advanced template input to job wizard
  app/controllers/ui_job_wizard_controller.rb
  webpack/JobWizard/JobWizard.js
  webpack/JobWizard/JobWizard.scss
  webpack/JobWizard/JobWizardSelectors.js
  webpack/JobWizard/__tests__/fixtures.js
  webpack/JobWizard/__tests__/integration.test.js
  webpack/JobWizard/steps/AdvancedFields/AdvancedFields.js
  webpack/JobWizard/steps/AdvancedFields/Fields.js
  webpack/JobWizard/steps/AdvancedFields/__tests__/AdvancedFields.test.js
  webpack/JobWizard/steps/AdvancedFields/__tests__/__snapshots__/AdvancedFields.test.js.snap
  webpack/JobWizard/steps/form/FormHelpers.js
  webpack/JobWizard/steps/form/Formatter.js
  webpack/JobWizard/steps/form/NumberInput.js
  webpack/JobWizard/steps/form/__tests__/Formatter.test.js
  webpack/JobWizard/steps/form/__tests__/__snapshots__/Formatter.test.js.snap
  webpack/__mocks__/foremanReact/components/SearchBar.js
Labels: Needs re-review, Needs testing, Waiting on contributor

#558 Fixes #31500 - Add basic schedule to job wizard
  webpack/JobWizard/JobWizard.js
  webpack/JobWizard/JobWizard.scss
  webpack/JobWizard/JobWizardConstants.js
  webpack/JobWizard/steps/Schedule/QueryType.js
  webpack/JobWizard/steps/Schedule/RepeatOn.js
  webpack/JobWizard/steps/Schedule/ScheduleType.js
  webpack/JobWizard/steps/Schedule/StartEndDates.js
  webpack/JobWizard/steps/Schedule/__tests__/StartEndDates.test.js
  webpack/JobWizard/steps/Schedule/index.js
  webpack/JobWizard/steps/form/SelectField.js
Labels: Needs testing

#597 Fixes #32721 - Add GraphQL queries for JobInvocations
  app/graphql/types/job_invocation.rb
  foreman_remote_execution.gemspec
  lib/foreman_remote_execution/engine.rb
  test/graphql/queries/job_invocation_query_test.rb
  test/graphql/queries/job_invocations_query_test.rb
Labels: Needs testing, Not yet reviewed

#612 Fixes #32992 - some rex settings are translated twice
  app/models/setting/remote_execution.rb
Labels: Needs testing, Not yet reviewed

#610 Try capturing logs from GH actions
  .github/workflows/ruby_ci.yml
  test/unit/job_invocation_composer_test.rb
Labels: Needs re-review, Needs testing, Waiting on contributor

#620 Refs #32606 - Make method names match
  lib/foreman_remote_execution_core/utils.rb
Labels: Needs testing, Not yet reviewed

#616 Fixes #32986 - Slow loading of hosts in job invocation page
  app/helpers/remote_execution_helper.rb
Labels: Needs testing

#609 Fixes #29950 - Map Run Puppet Once template to its feature
  app/views/templates/ssh/module_action.erb
  app/views/templates/ssh/puppet_run_once.erb
Labels: Needs testing, Not yet reviewed

#621 Refs #27770 - Add support for ed25519 keys with net-ssh ~> 4.2.0
  foreman_remote_execution_core.gemspec
Labels: Needs testing, Not yet reviewed

#555 Fixes #31460 - add description field to job wizard
  webpack/JobWizard/JobWizard.js
  webpack/JobWizard/steps/AdvancedFields/AdvancedFields.js
  webpack/JobWizard/steps/AdvancedFields/DescriptionField.js
  webpack/JobWizard/steps/AdvancedFields/__tests__/DescriptionField.test.js
Labels: Needs testing

#634 Refs #33024 - Pass feature as a string
  app/views/templates/ssh/module_action.erb
Labels: Needs testing

#637 Revert "Refs #27770 - Add support for ed25519 keys with net-ssh ~> 4.…
  foreman_remote_execution_core.gemspec
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#596 Refs #31267 - align recent jobs card with the current design
  webpack/react_app/components/RecentJobsCard/JobStatusIcon.js
  webpack/react_app/components/RecentJobsCard/RecentJobsCard.js
  webpack/react_app/components/RecentJobsCard/RecentJobsTable.js
  webpack/react_app/components/RecentJobsCard/constants.js
  webpack/react_app/components/RecentJobsCard/styles.css
  webpack/react_app/components/RecentJobsCard/styles.scss
  webpack/react_app/extend/fillRecentJobsCard.js
Labels: Needs re-review, Needs testing

#641 Fixes #27769 - Catch exception when using ed25519 algorithm
  lib/foreman_remote_execution_core/script_runner.rb
Labels: Needs testing
