Repository theforeman/foreman_remote_execution, pull requests merged in 2022-06, with the labels that each got.

#724 Fixes #34936 - Job wizard - Add SSH User field
  webpack/JobWizard/steps/AdvancedFields/AdvancedFields.js
  webpack/JobWizard/steps/AdvancedFields/Fields.js
  webpack/JobWizard/steps/AdvancedFields/__tests__/AdvancedFields.test.js
  webpack/JobWizard/steps/ReviewDetails/index.js
  webpack/JobWizard/submit.js
Labels: Needs testing

#719 Fixes #34871 - Allow searching on tasks by REX feature
  app/models/concerns/foreman_remote_execution/foreman_tasks_task_extensions.rb
  app/models/job_template.rb
  app/models/template_invocation.rb
Labels: Needs testing

#698 Fixes #34555 - redesign scheduling step job wizard
  webpack/JobWizard/JobWizard.js
  webpack/JobWizard/JobWizard.scss
  webpack/JobWizard/JobWizardConstants.js
  webpack/JobWizard/__tests__/integration.test.js
  webpack/JobWizard/steps/ReviewDetails/index.js
  webpack/JobWizard/steps/Schedule/PurposeField.js
  webpack/JobWizard/steps/Schedule/QueryType.js
  webpack/JobWizard/steps/Schedule/RepeatHour.js
  webpack/JobWizard/steps/Schedule/RepeatOn.js
  webpack/JobWizard/steps/Schedule/ScheduleFuture.js
  webpack/JobWizard/steps/Schedule/ScheduleRecurring.js
  webpack/JobWizard/steps/Schedule/ScheduleType.js
  webpack/JobWizard/steps/Schedule/StartEndDates.js
  webpack/JobWizard/steps/Schedule/__tests__/Schedule.test.js
  webpack/JobWizard/steps/Schedule/__tests__/StartEndDates.test.js
  webpack/JobWizard/steps/Schedule/index.js
  webpack/JobWizard/submit.js
Labels: Needs testing

#692 Refs #34396 - reflect the report name change
  lib/foreman_remote_execution/engine.rb
  test/unit/job_invocation_report_template_test.rb
  test/unit/job_invocation_test.rb
Labels: Needs testing, Waiting on contributor

#725 Fixes #34970 - Allow enabling REX pull in registration form
  app/controllers/foreman_remote_execution/concerns/api/v2/registration_commands_controller_extensions.rb
  app/controllers/foreman_remote_execution/concerns/api/v2/registration_controller_extensions.rb
  lib/foreman_remote_execution/engine.rb
  webpack/react_app/components/RegistrationExtension/RexPull.js
  webpack/react_app/extend/Fills.js
Labels: Needs testing

#728 Fixes #35003 - Change recent jobs card weight
  webpack/react_app/extend/Fills.js
Labels: Needs testing

#648 Fixes #33397 - Propagate validation errors from triggering
  app/models/job_invocation_composer.rb
  test/functional/api/v2/job_invocations_controller_test.rb
Labels: Needs testing, Needs re-review

#730 Fixes #35077 - Cant run job wizard with weekly
  webpack/JobWizard/steps/Schedule/RepeatWeek.js
  webpack/JobWizard/submit.js
Labels: Needs testing

#732 Fixes #35086 - allow to set advanced install_package options
  app/views/templates/script/package_action.erb
Labels: Needs testing
