Repository theforeman/foreman_remote_execution, pull requests merged in 2022-09, with the labels that each got.

#754 refs #34970 - Host Registration - put interface back
  webpack/react_app/extend/Fills.js
Labels: Needs testing

#751 Fixes #35426 - Add ouiaId prop to all supported components in host details
  webpack/react_app/components/HostKebab/KebabItems.js
  webpack/react_app/components/RecentJobsCard/RecentJobsCard.js
  webpack/react_app/components/RecentJobsCard/RecentJobsTable.js
Labels: Needs testing, Waiting on contributor, CP/3.3-compatible

#752 Fixes #35437 - host details jobs change from list to table
  webpack/react_app/components/RecentJobsCard/RecentJobsTable.js
Labels: Needs testing, CP/3.3-compatible

#755 Fixes #35471 - Slot & Fill renders only one component
  webpack/react_app/extend/Fills.js
Labels: Needs testing

#750 Fixes #35408 - Add time_to_pickup setting
  app/models/job_invocation_composer.rb
  app/models/remote_execution_provider.rb
  app/views/job_invocations/_form.html.erb
  db/migrate/20220822155946_add_time_to_pickup_to_job_invocation.rb
  lib/foreman_remote_execution/engine.rb
Labels: Needs testing
