Repository theforeman/foreman_remote_execution, pull requests merged in 2022-05, with the labels that each got.

#713 Fixes #31845 - Honor default input values set in template
  app/models/job_invocation_composer.rb
  app/models/job_template.rb
Labels: Needs testing

#717 Fixes #34835 - Open Cockpit console in a new tab
  webpack/react_app/components/HostKebab/KebabItems.js
Labels: Needs testing

#721 Fixes #32104 - Retain tasks used for errata reporting for longer time
  app/lib/actions/remote_execution/run_host_job.rb
  app/lib/actions/remote_execution/run_hosts_job.rb
Labels: Needs testing, Waiting on contributor

#720 Refs #34876 - Fix slot id for recent jobs card
  lib/foreman_remote_execution/engine.rb
  webpack/react_app/extend/fillRecentJobsCard.js
Labels: Needs testing

#718 Extract strings for translation
  locale/action_names.rb
  locale/de/foreman_remote_execution.po
  locale/en/foreman_remote_execution.po
  locale/en_GB/foreman_remote_execution.po
  locale/es/foreman_remote_execution.po
  locale/foreman_remote_execution.pot
  locale/fr/foreman_remote_execution.po
  locale/ja/foreman_remote_execution.po
  locale/ko/foreman_remote_execution.po
  locale/pt_BR/foreman_remote_execution.po
  locale/ru/foreman_remote_execution.po
  locale/zh_CN/foreman_remote_execution.po
  locale/zh_TW/foreman_remote_execution.po
Labels: Needs testing, Waiting on contributor

#669 Fixes #33844 - wizard multiple select closes after select
  webpack/JobWizard/steps/form/SearchSelect.js
Labels: Needs testing

#694 Fixes #34471 - Add bookmarks to jobs targeting host
  webpack/react_app/components/TargetingHosts/TargetingHostsConsts.js
  webpack/react_app/components/TargetingHosts/TargetingHostsPage.js
  webpack/react_app/components/TargetingHosts/__tests__/__snapshots__/TargetingHostsPage.test.js.snap
  webpack/react_app/components/TargetingHosts/__tests__/fixtures.js
  webpack/react_app/components/TargetingHosts/index.js
Labels: Needs testing

#703 Fixes #34502 - Add SSH User field in job invocation
  app/controllers/api/v2/job_invocations_controller.rb
  app/models/job_invocation_composer.rb
  app/models/ssh_execution_provider.rb
  app/views/api/v2/job_invocations/base.json.rabl
  app/views/job_invocations/_card_target_hosts.html.erb
  app/views/job_invocations/_form.html.erb
  db/migrate/20220331112719_add_ssh_user_to_job_invocation.rb
Labels: Needs testing

#701 Fixes #34606 - Job wizard build incorrect hostgroup search
  webpack/JobWizard/__tests__/fixtures.js
  webpack/JobWizard/steps/HostsAndInputs/SelectGQL.js
  webpack/JobWizard/steps/HostsAndInputs/SelectedChips.js
  webpack/JobWizard/steps/HostsAndInputs/buildHostQuery.js
  webpack/JobWizard/steps/HostsAndInputs/hostgroups.gql
  webpack/JobWizard/steps/HostsAndInputs/hosts.gql
  webpack/__mocks__/foremanReact/common/globalIdHelpers.js
Labels: Needs testing

#722 Fixes #34900 - Make 'Schedule a job' button secondary
  webpack/react_app/components/FeaturesDropdown/index.js
Labels: Needs testing

#723 Move away from corrupted gem cache
  .github/workflows/ruby_ci.yml
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#726 Try fixing CI again
  .github/workflows/ruby_ci.yml
Labels: Needs testing, Not yet reviewed, Waiting on contributor
