Repository theforeman/foreman_remote_execution, pull requests merged in 2022-11, with the labels that each got.

#733 EXPLAIN ANALYZE for proxy selection
  lib/foreman_remote_execution/engine.rb
  lib/foreman_remote_execution/tasks/explain_proxy_selection.rake
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#756 Fixes #35494 - Replace Foreman to_bool with rails implementation
  app/controllers/job_templates_controller.rb
Labels: Needs testing

#739 Fixes #35218 - Store job outputs outside of tasks
  app/lib/actions/remote_execution/proxy_action.rb
  app/lib/actions/remote_execution/run_host_job.rb
  app/lib/actions/remote_execution/template_invocation_progress_logging.rb
  app/models/template_invocation.rb
  app/models/template_invocation_event.rb
  db/migrate/20220713095705_create_template_invocation_events.rb
  foreman_remote_execution.gemspec
Labels: Needs testing, Waiting on contributor, Needs re-review
