Repository theforeman/foreman_remote_execution, pull requests merged in 2022-02, with the labels that each got.

#689 Fixes #34362 - fix 'host detail' button to include the new page
  app/helpers/remote_execution_helper.rb
Labels: Needs testing

#690 Refs #34362 - fix host path to use new host
  app/views/job_invocations/_preview_hosts_list.html.erb
  app/views/template_invocations/show.html.erb
Labels: Needs testing

#693 Fixes #34452 - Allow hosts to have no execution interface
  app/models/concerns/foreman_remote_execution/nic_extensions.rb
  test/unit/concerns/host_extensions_test.rb
Labels: Needs testing

#695 Make rubocop happy
  locale/action_names.rb
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#696 Prevent ssh action for zypper to return 0 on failure
  app/views/templates/ssh/package_action.erb
Labels: Needs testing, Waiting on contributor
